Name:           ros-indigo-evapc-start
Version:        0.0.6
Release:        0%{?dist}
Summary:        ROS evapc_start package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/evapc_ros
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-master-discovery-fkie
Requires:       ros-indigo-master-sync-fkie
Requires:       ros-indigo-openni-launch
Requires:       ros-indigo-rplidar-ros
BuildRequires:  ros-indigo-catkin

%description
The evapc_start provides roslaunch scripts for starting the Evarobot base
functionality in PC.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Mar 10 2016 Mehmet Akcakoca <akcakocamehmet@gmail.com> - 0.0.6-0
- Autogenerated by Bloom

